# -*- coding: utf-8 -*-
"""
This process builds and deploys the Online Northwest website. The site uses
Jekyll to generate static HTML files and rsync to deploy them to a web server.
"""

from fabric.api import *
from fabric.contrib import files
from fabric.contrib.project import *
import config

env.roledefs = config.settings

def _set_env():
    """
    Load env.hosts and env.site_root for the deployment task.
    Role definitions and some notes about their configuration are in config.py.
    """
    env.site_root = env.roledefs[env.effective_roles[0]]['site_root']


@task
def deploy():
    """
    Two steps:
    1. Build the site locally using jekyll build.
    2. Use rsync to copy the site to the target server.
    """
    _set_env()
    local('bundle install && bundle exec jekyll build')
    rsync_project(remote_dir=env.site_root, local_dir='./_site/', delete=True)


@task
def clean():
    """
    Clean up local files generated by the build and deploy process.
    """
    local('rm -rf _site')


@task
def test():
    """
    Test connection to the target server by running `ls` on the website filesystem.
    """
    _set_env()
    run('ls -latr {0}'.format(env.site_root))
